config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  get 'sessions/new'
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/items/search' => 'items#search_all_items', as: 'search_items'


  # Sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/new_item', to: 'users#new_item', as:'new_item'
  get '/users/:id/my_items', to: 'items#my_items', as:'my_items'
  get '/users/:id/my_reviews', to: 'reviews#my_reviews', as:'my_reviews'

  # Routes for index page item categories
  get 'category/art_items', to: 'welcome#art_items', as:'art_items'
  get 'category/beauty_items', to: 'welcome#beauty_items', as:'beauty_items'
  get 'category/books_items', to: 'welcome#books_items', as:'books_items'
  get 'category/clothing_items', to: 'welcome#clothing_items', as:'clothing_items'
  get 'category/property_items', to: 'welcome#property_items', as:'property_items'
  get 'category/other_items', to: 'welcome#other_items', as:'other_items'

  resources :users, controller:'users'
  resources :items, controller: 'items'

  # Routes for user items
  resources :users, only: [:new, :edit, :show, :update, :create] do
    resource :items
  end

  post 'users/:user_id/items/:id/review', to: 'reviews#create', as:'create_review'
  post 'items/:id/bid', to: 'bids#create', as:'create_bid'
  post 'items/:id/braintree/checkout' => 'braintree#checkout', as: 'braintree_checkout'

end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :items, dependent: :destroy
    has_many :bids, dependent: :destroy
    has_secure_password
    has_many :authentications, dependent: :destroy
    has_many :reviews, dependent: :destroy

    # VALIDATIONS
    validates_uniqueness_of :email
    validates :email, presence: true
    validates :username, presence: true
    validates :age, :numericality => true, :allow_nil => true
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i 
    validates_format_of :email, with: EMAIL_REGEX

    def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
        username: auth_hash["info"]["name"],
        email: auth_hash["info"]["email"],
        password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
    end

    # grab google to access google for user data
    def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to root_url
        else
            redirect_to root_url
        end
    end
    
    def edit
    end

    def show
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to @user
    end

    def new_item
        respond_to do |format|
            format.html {}
            format.js
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password_digest, :password, :age, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new_item.html.erb
<h1>Sell Something</h1>
<%= form_with scope: :item, url: user_items_path(current_user.id), :html => {:multipart => true}, local: true do |form| %>
    <p>
        <%= form.label :"Title" %><br>
        <%= form.text_field :name, class:'form-control' %>
    </p>
    <p>
        <%= form.label :"Description" %><br>
        <%= form.text_area :description, class:'form-control' %>
    </p>
    <p>
        <%= form.label :"Start bidding price" %><br>
        <%= form.text_field :price, class:'form-control' %>
    </p>
    <p>
        <%= form.label :"Immediate purchase price" %><br>
        <%= form.text_field :highprice, class:'form-control' %>
    </p>
    <p>
        <%= form.label :"Condition" %><br>
        <%= form.select :condition, ['new', 'used'] %>
    </p>
    <p>
        <%= form.label :"Category" %><br>
        <%= form.select :category, ['art', 'beauty', 'books', 'clothing', 'other', 'property'] %>
    </p>
    <p>
        <%= form.label :'Image' %>
        <%= form.file_field :image, class:'form-control' %>
    </p>
    <p>
        <%= form.submit 'Create', class:'btn btn-outline-success', style:'width:100%' %>
    </p>
<% end %>

app/views/users/new_item.js.erb
$('#new_item').html("<%= escape_javascript(render :partial => 'new_item')%>")

app/views/users/show.html.erb
<div class='container'>
    <div class='pt-2 mt-5'style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <img src=<%= @user.image_url(:thumb).to_s %> style="width:8rem; border-radius:65px;" alt="Card image cap"><br>
        <div style="display:flex; justify-content:center; margin-bottom:1rem;">
            <h2 id='username' style="float:left; margin:0px"><%= @user.username %></h2><br>
                <!-- Button trigger modal -->
            <% if @user.id == current_user.id %>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#exampleModalCenter" style="background-color:transparent; float:left; top:0px; padding:0px; border:0px">
                    <%= image_tag 'edit3.png', style:'width:1rem; opacity:0.5;' %>
                </button>
            <% end %>
        </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <%= form_for @user, :html => {:multipart => true}, local: true do |form| %>
                <p>
                    <%= form.label :"username" %><br>
                    <%= form.text_field :username %>
                </p>
                <p>
                    <%= form.file_field :image %>
                    <%= form.button :submit => "", class: "btn btn-primary btn-xs" %>
                </p>
            <% end %>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
    </div>
    </div>

    <div class='container' style='margin:auto;'>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" style="display:flex; justify-content:center;">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#" >Info | History</a>
            </li>
            <li class="nav-item">
                <%= link_to "Items", my_items_path(@user.id), remote: true, class:'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Reviews", my_reviews_path(@user.id), remote: true, class:'nav-link' %>
            </li>
            <% if @user.id == current_user.id %>
                <li>
                    <%= link_to "Sell", new_item_path(current_user.id), remote: true, class:'nav-link' %>
                </li>
            <% end %>
            </ul>
        </div>
        </nav>
    </div>
    <div id="new_item">
    </div>
</div>