config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  get 'sessions/new'
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/items/search' => 'items#search_all_items', as: 'search_items'


  # Sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/new_item', to: 'users#new_item', as:'new_item'
  get '/users/:id/my_items', to: 'items#my_items', as:'my_items'
  get '/users/:id/my_reviews', to: 'reviews#my_reviews', as:'my_reviews'

  # Routes for index page item categories
  get 'category/art_items', to: 'welcome#art_items', as:'art_items'
  get 'category/beauty_items', to: 'welcome#beauty_items', as:'beauty_items'
  get 'category/books_items', to: 'welcome#books_items', as:'books_items'
  get 'category/clothing_items', to: 'welcome#clothing_items', as:'clothing_items'
  get 'category/property_items', to: 'welcome#property_items', as:'property_items'
  get 'category/other_items', to: 'welcome#other_items', as:'other_items'

  resources :users, controller:'users'
  resources :items, controller: 'items'

  # Routes for user items
  resources :users, only: [:new, :edit, :show, :update, :create] do
    resource :items
  end

  post 'users/:user_id/items/:id/review', to: 'reviews#create', as:'create_review'
  post 'items/:id/bid', to: 'bids#create', as:'create_bid'
  post 'items/:id/braintree/checkout' => 'braintree#checkout', as: 'braintree_checkout'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def art_items
    @art_items = Item.where(category:'art')
  end

  def beauty_items
    @beauty_items = Item.where(category:'beauty')
  end

  def books_items
    @books_items = Item.where(category:'books')
  end

  def clothing_items
    @clothing_items = Item.where(category:'clothing')
  end

  def property_items
    @property_items = Item.where(category:'property')
  end

  def other_items
    @other_items = Item.where(category:'other')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_art_items.html.erb
<h1>Art</h1>
<div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @art_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/_beauty_items.html.erb
<h1>Beauty</h1><div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @beauty_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/_books_items.html.erb
<h1>Books</h1>
<div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @books_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/_clothing_items.html.erb
<h1>Clothing</h1>
<div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @clothing_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/_other_items.html.erb
<h1>Other</h1>
<div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @other_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/_property_items.html.erb
<h1>Property</h1>
<div class="card-deck" id="card-deck" style="display:flex; justify-content:space-between;">
    <% @property_items.each do |item| %>
        <% next if item.image_url == nil %>
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= item.image_url(:thumb).to_s %> alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        </div>
    <% end %>
</div>

app/views/welcome/art_items.js.erb
$('#index-categories').html("<%= escape_javascript(render :partial => 'art_items')%>")

app/views/welcome/beauty_items.js.erb
$('#index-categories').html("<%=escape_javascript(render :partial => 'beauty_items')%>")

app/views/welcome/books_items.js.erb
$('#index-categories').html("<%= escape_javascript(render :partial => 'books_items')%>")

app/views/welcome/clothing_items.js.erb
$('#index-categories').html("<%= escape_javascript(render :partial => 'clothing_items')%>")

app/views/welcome/index.html.erb
<% if logged_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" style="display:flex; justify-content:center;">
            <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Art", art_items_path, remote: true, class:'nav-link' %>
            </li>
            <li>
                <%= link_to "Beauty", beauty_items_path, remote: true, class:'nav-link' %>
            </li>
            <li>
                <%= link_to "Books", books_items_path, remote: true, class:'nav-link' %>
            </li>
            <li>
                <%= link_to "Clothing", clothing_items_path, remote: true, class:'nav-link' %>
            </li>
            <li>
                <%= link_to "Property", property_items_path, remote: true, class:'nav-link' %>
            </li>
            <li>
                <%= link_to "Other", other_items_path, remote: true, class:'nav-link' %>
            </li>
            </ul>
        </div>
    </nav>
<% end %>

<div class="container-fluid">
  <div class="container-fluid">
    <div class="row">
      <div id = "hero-showcase-left" class="container-fluid d-flex">
        <div class="col-6 d-inline-block mr-2 pl-0 mt-3">
        <%#= image_tag 'girl.jpeg', style:'width:100%' %>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="height:450px !important">
            <div class="carousel-inner">
                <div class="carousel-item active">
                <%= image_tag 'girl.jpeg', style:'width:100%', class:'d-block w-100' %>
                </div>
                <div class="carousel-item">
                <%= image_tag 'toofaced.gif', style:'width:100%; height:450px !important', class:'d-block w-100' %>
                </div>
                <div class="carousel-item">
                <%= image_tag 'cocacola.jpg', style:'width:100%; height:450px !important', class:'d-block w-100' %>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        </div>
        <div id="hero-showcase-right" class="col-md-6 d-inline-block mt-3 bg-white shadow-lg rounded border border-muted">
        <%if logged_in? %><h1 class="pl-5 pr-5 pt-1 mt-1" style="font-size: 42px;"><strong>Welcome!</strong></h1><% end %>
          <h1 class="pl-5 pr-5 pt-5 mt-5" style="font-size: 42px;"><strong>eBoy</strong> the greatest online store <strong>in Malaysia.</strong></h1>
          <p class="hero pl-5 pr-5 pt-4"> Buy something for yourself or sell one of your preloved items to someone else.</p>
          <p class="hero pl-5 pr-5 pb-3"> Shop from our various categories and have something new delivered to your doorstep- <strong>Let's Shop.</strong></p>
          <% if logged_out? %>
            <div class="container pl-5 text-center">
              <%= form_for :user, url: users_path, local:true, :method => 'post', :html => {:multipart => true} do |form| %>
                <%= form.text_field :username, class:'form-control mb-2', placeholder:'Username'%>
                <%= form.text_field :email, type: 'email', class:'form-control mb-2', placeholder:'Email', id:'email_signup' %>
                <%= form.password_field :password, class:'form-control mb-3', placeholder:'Password', id:'password_signup' %>
                <%= form.text_field :age, class:'form-control mb-3', placeholder:'Age' %>
                <%= form.file_field :image, class:'form-control mb-3', placeholder:'Image' %>
                <%= form.submit 'Sign Up', class:'btn btn-primary mb-3' %>
                <button class="btn btn-outline-success mb-3" type="button"  data-toggle="modal" data-target="#exampleModal">
                  Sign In
                </button>
                <% end %>
            </div>
          <% end %>
        </div>
    </div>
    <div class="modal" id="exampleModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="width:800px;">
                <div class="container border border-dark">
                    <div class="row">
                        <div class="col-md-4 login-bg text-white text-center">
                            <h2><i class="fas fa-brain fa-5x mt-3"></i></h2>
                        </div>
                            <div class="col-md-8">
                                <h1 class="text-center mt-3 login-text">Login To Your Account</h1>
                                <label class="sr-only" for="inlineFormInputGroupUsername2">Email</label>
                                <%= form_for :session, url: login_path do |form| %>
                                <div class="input-group mb-2 mr-sm-2 mt-5">
                                    <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fas fa-user"></i></div>
                                    </div>
                                    <%= form.text_field :email, type: 'email', class:'form-control', id:'inlineFormInputGroupUsername2', placeholder:'Email' %>
                                </div>
                                <label class="sr-only" for="inlineFormInputGroupUsername2">Email</label>
                                <div class="input-group mb-2 mr-sm-2">
                                    <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fas fa-lock"></i></div>
                                    </div>
                                    <%= form.password_field :password, class:'form-control', id:'inlineFormInputGroupUsername2', placeholder:'Password'%>
                                </div>
                                    <%= form.submit 'Sign In', class:'btn btn-primary mt-3 mb-3' %>
                                    <%= link_to "Sign in with Google", "/auth/google_oauth2", class:'btn btn-outline-success mt-3 mb-3' %>
                                <% end %>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
<div class='container mt-2' style="text-align: center; height:100%">
    <div id='index-categories' style='height:100%;'>
    </div>
</div>

app/views/welcome/other_items.js.erb
$('#index-categories').html("<%= escape_javascript(render :partial => 'other_items')%>")

app/views/welcome/property_items.js.erb
$('#index-categories').html("<%= escape_javascript(render :partial => 'property_items')%>")