config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  get 'sessions/new'
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/items/search' => 'items#search_all_items', as: 'search_items'


  # Sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/new_item', to: 'users#new_item', as:'new_item'
  get '/users/:id/my_items', to: 'items#my_items', as:'my_items'
  get '/users/:id/my_reviews', to: 'reviews#my_reviews', as:'my_reviews'

  # Routes for index page item categories
  get 'category/art_items', to: 'welcome#art_items', as:'art_items'
  get 'category/beauty_items', to: 'welcome#beauty_items', as:'beauty_items'
  get 'category/books_items', to: 'welcome#books_items', as:'books_items'
  get 'category/clothing_items', to: 'welcome#clothing_items', as:'clothing_items'
  get 'category/property_items', to: 'welcome#property_items', as:'property_items'
  get 'category/other_items', to: 'welcome#other_items', as:'other_items'

  resources :users, controller:'users'
  resources :items, controller: 'items'

  # Routes for user items
  resources :users, only: [:new, :edit, :show, :update, :create] do
    resource :items
  end

  post 'users/:user_id/items/:id/review', to: 'reviews#create', as:'create_review'
  post 'items/:id/bid', to: 'bids#create', as:'create_bid'
  post 'items/:id/braintree/checkout' => 'braintree#checkout', as: 'braintree_checkout'

end

app/models/item.rb
class Item < ApplicationRecord
  # VALIDATIONS
  validates :price, :numericality => true
  validate :validate_prices

  belongs_to :user
  has_many :bids, dependent: :destroy
  enum category: { art: 'art', beauty:'beauty', books: 'books', clothing: 'clothing', property: 'property', other: 'other'}
  mount_uploader :image, ImageUploader

  def self.search_items(query)
    where("name ILIKE :name", name: "%#{query}%")
  end
  
  private
  
  def validate_prices
    if highprice <= price
      errors.add(:highprice, 'must be greater than price')
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
    end

    def my_index
    end

    def show
        @item = Item.find(params[:id])
        @item_bids = Item.find(params[:id]).bids.order("created_at DESC")
        @user = User.find(@item.user_id)
        @highest_bid = Bid.order("amount DESC").first
    end

    def new
        @item = Item.new()
    end

    def create
        @item = Item.new(item_params)
        @item.update(user_id:current_user.id)
        if @item.save
            redirect_to edit_item_path(@item.id)
        else
            redirect_to user_path(current_user.id)
        end
    end

    def edit 
        @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to @item
    end

    def my_items
        @user = User.find(params[:id])
        @my_items = @user.items
        respond_to do |format|
            format.html {}
            format.js
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to user_path(current_user.id)
    end

    def search_all_items
        @items = Item.all
        @search_items = Item.search_items(params["searchitem"])
        @item = Item.find_by(name: params["searchitem"])

        respond_to do |format|
            format.html { redirect_to item_path(@item.id) }
            format.json { render json: @search_items.map{|i| i.name}}
        end
    end

    private

    def item_params
        params.require(:item).permit(:name, :description, :price, :used, :category, :place, :latitude, :longitude, :image, :condition, :highprice)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);
          function initMap2() {
            var lat = document.getElementById('item_latitude').value;
            var lng = document.getElementById('item_longitude').value;
            
            // if not defined create default position
            if (!lat || !lng){
                lat=51.5;
                lng=-0.125;
                document.getElementById('item_latitude').value = lat;
                document.getElementById('item_longitude').value = lng;
            }
            var myCoords = new google.maps.LatLng(lat, lng);
            var mapOptions = {
            center: myCoords,
            zoom: 14
            };
            var map = new google.maps.Map(document.getElementById('map2'), mapOptions);
            var marker = new google.maps.Marker({
                position: myCoords,
                animation: google.maps.Animation.DROP,
                map: map,
                draggable: true
            });
            // refresh marker position and recenter map on marker
            function refreshMarker(){
                var lat = document.getElementById('item_latitude').value;
                var lng = document.getElementById('item_longitude').value;
                var myCoords = new google.maps.LatLng(lat, lng);
                marker.setPosition(myCoords);
                map.setCenter(marker.getPosition());   
            }
            // when input values change call refreshMarker
            document.getElementById('item_latitude').onchange = refreshMarker;
            document.getElementById('item_longitude').onchange = refreshMarker;
            // when marker is dragged update input values
            marker.addListener('drag', function() {
                latlng = marker.getPosition();
                newlat=(Math.round(latlng.lat()*1000000))/1000000;
                newlng=(Math.round(latlng.lng()*1000000))/1000000;
                document.getElementById('item_latitude').value = newlat;
                document.getElementById('item_longitude').value = newlng;
            });
            // When drag ends, center (pan) the map on the marker position
            marker.addListener('dragend', function() {
                map.panTo(marker.getPosition());   
            });
        }
    </script>
<% end %>

<%= form_with(model: item, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mr-sm-2" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control mr-sm-2" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control mr-sm-2" %>
  </div>

  <div class="field">
      <%= form.label :"Condition" %><br>
      <%= form.select :condition, ['new', 'used'] %>
  </div>
  <div class="field">
      <%= form.label :"Category" %><br>
      <%= form.select :category, ['art', 'beauty', 'books', 'clothing', 'other', 'property']%>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, class: "form-control mr-sm-2" %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: "form-control mr-sm-2" %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: "form-control mr-sm-2" %>
  </div>

  <p>
    <div id="map2" style='width:100%; height:400px;'></div>
  </p>

  <div class="actions">
    <%= form.submit 'Update', class:'btn btn-outline-success' %>
  </div>
<% end %>

app/views/items/_my_items.html.erb
<div class='mt-3' style="padding-left:15px; padding-right:15px;">
    <% @my_items.each do |item| %>
    <div class="card flex-row flex-wrap mb-4">
            <div class="card-header border-0">
                <img src=<%= item.image_url(:thumb).to_s %> alt="">
            </div>
            <div class="card-block px-2">
                <h4 class="card-title"> <%= item.name %> | $<%= item.price %>.00 </h4>
                <p class="card-text"> <strong>Description</strong> <%= item.description %> </p>
                <p class="card-text"> <strong>Condition</strong> <%= item.condition %> </p>

            </div>
            <div class="w-100"></div>
            <div class="card-footer w-100 text-muted">
            <%= link_to 'View', item_path(item.id)%>
            </div>
        </div>
    <% end %>
</div>

app/views/items/edit.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);
          function initMap2() {
            var lat = document.getElementById('item_latitude').value;
            var lng = document.getElementById('item_longitude').value;
            
            // if not defined create default position
            if (!lat || !lng){
                lat=51.5;
                lng=-0.125;
                document.getElementById('item_latitude').value = lat;
                document.getElementById('item_longitude').value = lng;
            }
            var myCoords = new google.maps.LatLng(lat, lng);
            var mapOptions = {
            center: myCoords,
            zoom: 14
            };
            var map = new google.maps.Map(document.getElementById('map2'), mapOptions);
            var marker = new google.maps.Marker({
                position: myCoords,
                animation: google.maps.Animation.DROP,
                map: map,
                draggable: true
            });
            // refresh marker position and recenter map on marker
            function refreshMarker(){
                var lat = document.getElementById('item_latitude').value;
                var lng = document.getElementById('item_longitude').value;
                var myCoords = new google.maps.LatLng(lat, lng);
                marker.setPosition(myCoords);
                map.setCenter(marker.getPosition());   
            }
            // when input values change call refreshMarker
            document.getElementById('item_latitude').onchange = refreshMarker;
            document.getElementById('item_longitude').onchange = refreshMarker;
            // when marker is dragged update input values
            marker.addListener('drag', function() {
                latlng = marker.getPosition();
                newlat=(Math.round(latlng.lat()*1000000))/1000000;
                newlng=(Math.round(latlng.lng()*1000000))/1000000;
                document.getElementById('item_latitude').value = newlat;
                document.getElementById('item_longitude').value = newlng;
            });
            // When drag ends, center (pan) the map on the marker position
            marker.addListener('dragend', function() {
                map.panTo(marker.getPosition());   
            });
        }
    </script>
<% end %>

<div class='container'>
    <h1> Where are you selling from? </h1>

    <%= form_for @item, local: true do |form| %>
    <div class="field">
        <%= form.label :latitude %>
        <%= form.text_field :latitude, class:'form-control'%>
    </div>

    <div class="field">
        <%= form.label :longitude %>
        <%= form.text_field :longitude, class:'form-control' %>
    </div>

    <p>
        <div id="map2" style='width:100%px; height:400px; text-align:center;'></div>
    </p>

    <div class="actions">
        <%= form.submit 'Enter Location', class:'btn btn-outline-primary'%>
    </div>
    <% end %>
</div>

app/views/items/my_items.js.erb
$('#new_item').html("<%= escape_javascript(render :partial => 'my_items')%>")

app/views/items/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@item.latitude%>, <%=@item.longitude%>)
    });
  </script>
<% end %>

<div class='container' style="margin:auto;">
    <div>
        <h1><%= @item.name %> Status: <%= @item.status.titlecase %> </h1>
        <% if @item.user_id == current_user.id %>
            <button class="btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Update 
            </button>
            <%= link_to 'Delete', item_path(@item.id), class:"btn btn-outline-danger",
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        <% end %>
        <% if @item.status == 'open' %>
            <%= link_to "Make Payment", braintree_new_path(@item.id) %>
        <% end %>
    </div>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <%= render 'form', item: @item %>
        </div>
    </div>


    <div class="card flex-row flex-wrap mb-4">
        <div class="card-header border-0">
            <img src=<%= @item.image_url(:thumb).to_s %> alt="">
        </div>
        <div class="card-block px-2">
            <h4 class="card-title"> Bidding Price: $ <%= @item.price %>.00 </h4>
            <h4 class="card-title"> Immediate Purchase Price: $ <%= @item.highprice %>.00 </h4>
            <p class="card-text"> <strong>Description</strong> <%= @item.description %> </p>
            <p class="card-text"> <strong>Condition</strong> <%= @item.condition.titlecase %> </p>
        </div>
        <div class="w-100"></div>
    </div>
</div>

<div class='container'>
    <div class='row'>
        <div class='col-sm'>
            <h2>Seller</h2>
            <div class="card border-0" style="width: 18rem;">
                <img class="card-img-top" src=<%=@user.image_url(:thumb).to_s%> style='border-radius:145px;' alt="Card image cap">
                <div class="card-body">
                </div>
            </div>
        </div>
        <div class='col-sm'>
            <div>
                <h2>Bidders | Highest bid: <% if @item.bids.count > 0 %> $ <%= @highest_bid.amount %> <% end %></h2>
                <!-- Button trigger modal -->
                <% if current_user.id != @item.user_id && @item.status == 'open' %>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal" style="position:absolute; right:0; top:0;">
                    Bid
                    </button>
                <% end %>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Update</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%= form_with scope: :bid, url: create_bid_path(@item.id), local: true do |form| %>
                                <%= form.label :"Amount" %>
                                <%= form.text_field :amount %>
                                <%= form.button :submit => "", class: "btn btn-primary btn-xs" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ^ End of modal -->

            <% @item_bids.each do |bid| %>
                <div class="card flex-row flex-wrap mb-4">
                    <div class="card-header border-0">
                        <img src=<%=bid.user.image_url(:thumb).to_s%> alt="" style="width:2.5rem; border-radius:35px;">
                    </div>
                    <div class="card-block px-2">
                        <h4 class="card-title" style="position:absolute; top:1rem;"><%=bid.user.username%></h4>
                        <h5 style="position:absolute; right:2.5rem; top:1rem;">$<%=bid.amount%></h5>
                    </div>
                    <div class="w-100"></div>
                    <div class="card-footer w-100 text-muted" style="padding:1px; text-align:right;">
                        <span><%= distance_of_time_in_words(Time.current - bid.created_at )%> ago </span>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class='row'>
    <p>
        <div id="map" style="width:100%; height:400px;"></div>
    </p>
    </div>
</div>
<script>
function initMap(lat, lng) {
    var myCoords = new google.maps.LatLng(lat, lng);
    var mapOptions = {
    center: myCoords,
    zoom: 14
    };
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);
    var marker = new google.maps.Marker({
        position: myCoords,
        map: map
    });
}
</script>