config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  get 'sessions/new'
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/items/search' => 'items#search_all_items', as: 'search_items'


  # Sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/new_item', to: 'users#new_item', as:'new_item'
  get '/users/:id/my_items', to: 'items#my_items', as:'my_items'
  get '/users/:id/my_reviews', to: 'reviews#my_reviews', as:'my_reviews'

  # Routes for index page item categories
  get 'category/art_items', to: 'welcome#art_items', as:'art_items'
  get 'category/beauty_items', to: 'welcome#beauty_items', as:'beauty_items'
  get 'category/books_items', to: 'welcome#books_items', as:'books_items'
  get 'category/clothing_items', to: 'welcome#clothing_items', as:'clothing_items'
  get 'category/property_items', to: 'welcome#property_items', as:'property_items'
  get 'category/other_items', to: 'welcome#other_items', as:'other_items'

  resources :users, controller:'users'
  resources :items, controller: 'items'

  # Routes for user items
  resources :users, only: [:new, :edit, :show, :update, :create] do
    resource :items
  end

  post 'users/:user_id/items/:id/review', to: 'reviews#create', as:'create_review'
  post 'items/:id/bid', to: 'bids#create', as:'create_bid'
  post 'items/:id/braintree/checkout' => 'braintree#checkout', as: 'braintree_checkout'

end

app/views/layouts/application.html.erb
  <head>
    <title>Bayarboss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag "//code.jquery.com/jquery-1.11.0.min.js" %>
    <%= javascript_include_tag "//code.jquery.com/jquery-migrate-1.2.1.min.js" %>
    <%= javascript_include_tag 'https://js.braintreegateway.com/web/3.6.3/js/client.min.js' %>
    <%= javascript_include_tag 'https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js' %>
    <%= javascript_include_tag 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.google_maps_api_key}" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
  <nav class="customnav navbar navbar-expand-lg navbar-dark sticky-top bg-white border-bottom border-muted">
  <a class="navbar-brand text-dark" href="/"><i class="fas fa-brain mr-1"></i>eBoy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
    <div class="navbar-links">
      <ul class="navbar-nav mr-auto">
      
      <% if logged_in? %>

      <li class='nav-item'>
        <%= form_with url: search_items_path, local: true, class:'form-inline my-2 my-lg-0' , :method => 'post', id: "search-items"  do |form| %>
          <%= form.text_field :searchitem, class: "form-control mr-sm-2", list: 'list', id:"main-search", placeholder:"Look for an item" %>
          <%= form.submit "Search", class:"btn btn-outline-primary my-2 my-sm-0" %>
          <datalist id="list"></datalist>
      <% end %>
      </li>

        <li class="nav-item">
          <%= link_to 'Profile', user_path(current_user.id), class: "nav-link mr-3", style:'color:black' %>
        </li>
        <li class="nav-item">
          <%=link_to 'Logout', logout_path, method: :delete, class: "nav-link mr-3", style:'color:black' %>
        </li>
      <% end %>

      </ul>
    </div>

  </div>
</nav>
    <%= yield %>
</body>

<script>
$(document).on('turbolinks:load', function(){

$("#search-items").on("keyup", function(){
  autocomplete()
});

function autocomplete(){
  $.ajax({
    url: '/items/search',
    type: 'POST',
    data: $("#search-items").serialize(),
    dataType: 'json',
    error: function() {
        console.log("Something went wrong");
    },
    success: function(data) {
      document.getElementById('list').innerHTML = '';
      $("#list").empty();

      var uniquedata = [];
      $.each(data, function(i, el){
          if($.inArray(el, uniquedata) === -1) uniquedata.push(el);
      });

      uniquedata.forEach(function(element) {
        var option = document.createElement("option");
        option.value = element;
        //append option to list
        $("#list").append(option);
      });
    }
  });
}
})
</script>